Reward/urls.py
from django.conf.urls import url
from django.contrib import admin
from Reward import views
from django.urls import include, path


app_name = 'Reward'
urlpatterns = [
    path('customer_dash', views.customer_dash, name='customer_dash'),
    path('login_user', views.login_user, name='login_user'),
    path('logt', views.logout_view, name='logt'),
    path('customer_reward', views.customer_reward, name='customer_reward'),
    path('rating', views.rating, name='rating'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('customer_report', views.customer_report, name='customer_report'),
    path('customer_details/<int:id>/', views.customer_details, name='customer_details'),
    path('export_customer_csv', views.export_customer_csv, name='export_customer_csv'),
    path('export_customer_csv2', views.export_customer_csv2, name='export_customer_csv2'),
    
    path('customers_report_list', views.customers_report_list, name='customers_report_list'),
    path('<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('<int:pk>/update/', views.customer_update, name='book_update'),
    path('create', views.customer_create, name='book_create'),
    path('create', views.customer_list, name='book_list'),
    path('search', views.search, name='search'),
    
   
]

customerReward/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Reward import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name="landing"),
    path('Reward/', include('Reward.urls', namespace='Reward'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Reward/models.py
# -*- coding: utf-8 -*-


from django.db import models
from datetime import datetime
# Create your models here.




from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings

class UserDetail(models.Model):
    user = models.ForeignKey(on_delete=models.CASCADE, to=User)
    gender = models.CharField(max_length=10)



    


# How to access any field of Register model from views.py Using  built in User model  of django 
# 1.request.user.register.telno or  request.user.register.city  or request.user.register.state or  request.user.register.role2
class Register(models.Model):

    user = models.ForeignKey(User, blank=True, default=False,on_delete=models.CASCADE, related_name="register")
    fname = models.CharField(blank=True, max_length=20,  default=False)
    sname = models.CharField(blank=True, max_length=30,  default=False)
    page = models.IntegerField(blank=True,  default=False)
    gender = models.CharField(blank=True, max_length=30,  default=False)
    telno = models.CharField(blank=True, max_length=20,  default=False)
    username = models.CharField(blank=True, max_length=20,default=False)
    password= models.CharField(max_length=50,  default=False)
    email = models.CharField(blank=True,max_length=50,  default=False)
    street = models.CharField(blank=True,max_length=50,  default=False)
    city = models.CharField(blank=True,max_length=20, default=False)
    state = models.CharField(blank=True,max_length=20,  default=False)
    role2 = models.CharField(max_length=20, default=False)
    access_right= models.CharField(max_length=30,default=False)
    account_blocked = models.BooleanField(default=False)
    profphoto = models.ImageField(upload_to ='uploads/', default=False) 
    code = models.CharField(max_length=12, blank=True,default=False)
    reward_amount = models.DecimalField(max_digits=16,
        decimal_places=5, default=0.0)


    
    def get_names(self):
        '''
        Return a users phonenumber
        '''
        text = '%s %s' % (self.fname, self.lname)
        try:
            text = text.encode('utf-8')
        except UnicodeEncodeError:
            pass
        return text

    def __unicode__(self):
        return self.username




@receiver(post_save, sender=User)
def create_user_register(sender, instance, created, **kwargs):
    if created:
        Register.objects.create(user=instance)



class Customer(models.Model):
 
    '''store login data'''
    date = models.DateTimeField(auto_now_add=True)
    fname = models.CharField(blank=True,max_length=50,  default=False)
    lname= models.CharField(blank=True,max_length=50,  default=False)
    phone = models.CharField(blank=True,max_length=50,  default=False)
    avscore = models.CharField(blank=True,max_length=50,  default=0)
    num_free = models.CharField(blank=True,max_length=50,  default=0)

class Rating(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    fname = models.CharField(blank=True,max_length=50,  default=False)
    lname= models.CharField(blank=True,max_length=50,  default=False)
    fullname = models.CharField(blank=True,max_length=50,  default=False)
    phone = models.CharField(blank=True,max_length=50,  default=False)
    score = models.FloatField()
    avscore = models.CharField(blank=True,max_length=50,  default=0)
    fscore = models.CharField(blank=True,max_length=50,  default=0)

    def __str__(self):
        return str(self.pk)

    @property
    def getavstar(self):
        if self.avscore == '':
            return 'None'
        return self.avscore




    

Reward/forms.py
from django import forms
from .models import Customer

from django.db import models

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('fname','lname', 'phone', )

Reward/views.py
from django.http import HttpResponse, Http404

from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User 
import re
from django.db.models import Avg, Max, Min, Sum
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from Reward.models import Rating
from Reward.models import Register 

from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login as auth_login
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth import logout


import csv

from django.http import HttpResponse

from django.views.decorators.csrf import csrf_exempt
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.conf import settings

from django.contrib import messages
import string 

import json
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
import datetime 
from django.db.models import Q
from Reward.utils import success_message, error_message
from django.http import JsonResponse
from django.template.loader import render_to_string
import random
import string

# payment

import requests
import time
from xml.etree import ElementTree as etree
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)   
import xmltodict
import json
import datetime
from datetime import timedelta
from lxml import objectify as xml_objectify



from django.shortcuts import render,get_object_or_404
from .models import  Customer
from .forms import  CustomerForm
from django.template.loader import render_to_string
from django.http import JsonResponse





# Video chat imports
import requests
import base64
import json
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.conf import settings
import random


def search(request):
    if request.is_ajax():
        q = request.GET.get('q')
        if q is not None:            
            results = Customer.objects.filter(  
                Q( fname__contains = q ) |
                Q( lname__contains = q ) )  
            context = {'results': results}        
            return render(request, 'Reward/results.html', context) 

         




@login_required
def render_view(request, template, data):
    '''
    wrapper for rendering views , loads RequestContext
    @request  request object
    @template  string
    @data  tumple
    '''
    context = RequestContext(request)

    # store login info

    # user permissions
    if request.user.is_authenticated():
        permissions = (request.user)
        print("User permissions %s " % (permissions))
        profile = {}
        try:
            profile = Register.objects.filter(user=request.user)
        except PageNotAnInteger:
            if request.user.is_superuser:
                create_superuser(request.user)         
                
        data.update({'profile': profile, 'perms': permissions})
    # for pagnation
    #debug(permissions, 'permissions')

    return render(request, template, data) 
  
   
   







def create_superuser(user):
    '''we are not doing this'''
    profile = Register.objects.create(user=user)



def get_user_permissions(user):
    '''return user permissions as a dict'''
    permissions = {}
    for x in Permission.objects.filter(user=user):
        permissions.update({x.codename: True})
    return permissions

    




def customer_dash(request):
    """Index page, force login here"""
    latest_questions = None
    context = RequestContext(request)

    context = {
    'latest_questions': latest_questions,
}

  
    return render(request, 'Reward/index.html', context) 







def logout_view(request):
    logout(request)
    return render(request,'Reward/index.html')
 



def landing(request):
    """Index page, force login here"""
    latest_questions = None
    context = RequestContext(request) 

    context = {
    'latest_questions': latest_questions,
}

    

    if  request.user.is_authenticated:
        print("User loged in")
        return render(request, 'Reward/login_user.html', context) 

  

    return render(request, 'Reward/login_user.html', context) 




@csrf_exempt
def login_user(request):
    # Like before, obtain the context for the user's hrequest.
    context = RequestContext(request)
    msg = ''
    response = None
    log = False
    convmem = ''
    phonedoctor = ''
    data = {}
    password = None
    username = None
    pay_status = None
    staf=False
    auth_error = False
    dname = None
    check_user = None
    dp_room1 = None
    dp_room = None
    check_doct = None
    dtelno=None
    type = None
    doctor_users =None
    doctor_users = None
    doctor_sms_data = {}
    ilness= ''
    role = None
    ordered_drugs = None
    query = None
    labtests = None

  

    try:
        check_user = Register.objects.get(username=request.user.username)
        role = check_user.role2
    except Exception as e:
        pass

    print("ROLEE")
    print(role)


    
    print("USEEERRR LOGGGGGGGG")
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        password = request.POST.get('password', None)
        username = request.POST.get('username', None)
        

        print("")
        try:
            check_user = Register.objects.get(password=password, username=username)
            role = check_user.role2
           
            print("Role %s" %(role))


        except Register.DoesNotExist:
            listing = None
           
            auth_error = True
            return render(request, 'Reward/login_user.html', {'log':log, 'auth_error':auth_error}) 
            
            
                

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
               



                print("Username", username)
                print("Password", password)

                request.session['username'] = request.user.username
                request.session['role'] = role



                print("Username 1", username)
                print("Password 1", password)
               
                return render(request, 'Reward/index.html', {'role':role, 'username':username}) 
                
                 


    return render(request, "Reward/login_user.html", {
        
            })






def dashboard(request):
    
    response = False
    post_values = {}
    context = RequestContext(request)
    Check_area = None
    saved_results = ''
    dp_room = ''
    username  = ''
    context = RequestContext(request)

    staff_no = " "
    staff_name  = " "
    labtest = True
   #GETTING RECORDS OF SQLITE3 
    saved_results=Customer.objects.order_by('-id')

    print(("Length %s" % (len(saved_results))))
    a = len(saved_results)
    role="customer_care"

    paginator = Paginator(saved_results, 10) # 6 posts per page
    page = request.GET.get('page')



    try:
        saved_results = paginator.page(page)
    except PageNotAnInteger:
        saved_results = paginator.page(1)
    except EmptyPage:
        saved_results = paginator.page(paginator.num_pages)




    try:
        if a >= 1:
            return render(request, 'Reward/dashboard.html', {'role':role,'books':saved_results}) 
    except Exception as e:
        return render(request, 'Reward/dashboard.html', {'role':role,'books':saved_results,'role':role}) 

    return render(request, 'Reward/dashboard2.html', {'role':role, 'books':saved_results}) 






@csrf_exempt
def rating(request):
    context = RequestContext(request)
    post_values = {}
    push_notif = {}
    AfricasTalk = None
    AfricasTalk  = AfricasTalk
    doctor_sms_data = {}
    dp_room = None
    password = None
    dname = None
    pdiog = None
    dtelno = None
    ptelno = None
    ge_city = None
    telno = ''
    doctor_users = None
    check_phone= None

    us = None
    dtelno = ''
    gender = None
    username = None
    check_record = None
    check_score  = None
    addedscore = False
    lname = None
    cust_score=None
    doctor_none = False
    if 'username' in request.session:
        username = request.session['username']
        print("Seesssion Username of Reward %s" % (username))

    
        
    if request.POST:
       
        post_values = request.POST.copy()
        fname = request.POST.get('fname', False)
        customer_id = request.POST.get('customer_id', False)
        

        free_product = request.POST.get('free_product', 0)
        rating = request.POST.get('rating', False)
        rating=float(rating)
        print("Rating %s" % (rating))

        try:
            check_record = Customer.objects.get(id=customer_id)
        except Exception as e:
            pass

        check_phone =   check_record.phone
        lname =   check_record.lname
        fname2 =   check_record.fname  
        fullname = "%s %s" % (fname2,lname)
        if fname and fname2:

            cust_score=Rating(fname=fname,lname=lname, fullname=fullname,
             score= int(rating), fscore=free_product, phone=check_phone)
            cust_score.save()

        if cust_score:
             addedscore= True

        try:
            check_scores = Rating.objects.filter(fname=fname)
        except Exception as e:

Reward/templates/Reward/includes/partial_customer_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'Reward:book_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new customer</h4>
  </div>
  <div class="modal-body">
    {% include 'Reward/includes/partial_customer_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create customer</button>
  </div>
</form>

Reward/templates/Reward/includes/partial_customer_delete.html
<form method="post" action="{% url 'Reward:book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm customer deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the customer  <strong>{{ book.fname}}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete customer</button>
  </div>
</form>

Reward/templates/Reward/includes/partial_customer_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

Reward/templates/Reward/includes/partial_customer_list.html
<tr class="border-0 d-lex">
      <th class="border-0 w-25">First Name</th>
<th  class="border-0 w-25">Last Name</th>
<th  class="border-0 w-25">Phone</th>
<th  class="border-0 w-25 float-righ" style="margin-left:0">Edit</th>
</tr>


{% for book in books %}


  <tr  class="d-fex" >
    <td class="w-25">{{ book.fname }}</td>
    <td class="w-25">{{ book.lname }}</td>
    <td class="w-25">  {{ book.phone}}</td>
    

     <td class="w-25" > <button type="button"
              class="btn btn-dark btn-sm floa-right ml-2 js-update-book"
              data-url="{% url 'Reward:book_update' book.id %}">

        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button></td>

 
  </tr>
{% empty %}
  <tr style="width:100PX">
    <td colspan="8" class="text-center bg-warning">No customer</td>
  </tr>
{% endfor %}

Reward/templates/Reward/includes/partial_customer_list2.html
{% for book in books %}
<tr class="d-fex"> 
    <td  class="w-25">{{ book.fname }}</td>
    <td  class="w-25">{{ book.lname }}</td>
    <td  class="w-25">{{ book.phone}}</td>
    <td  class="w-25">{{ book.avscore}}</td>

     <td  class="w-25"><a href="{% url 'Reward:customer_details' book.id %}"> {{ book.num_free}}</a></td>
 
  </tr>
{% empty %}
  <tr style="width:1000PX">
    <td colspan="8" class="text-center bg-warning">No customer</td>
  </tr>
{% endfor %}

Reward/templates/Reward/includes/partial_customer_list3.html
{% for book in books %}
  <tr  class="d-flex" >
    <td  class="w-25">{{ book.fname }}</td>
    <td class="w-25">{{ book.lname }}</td>
    <td class="w-25">{{ book.phone}}</td>
     <td class="w-25">{{ book.score}}</td>
      <td class="w-25">{{ book.date}}</td>
       <td class="w-25">{{ book.fscore}}</td>


    <td>

    </td>
  </tr>
{% empty %}
  <tr  class="d-flex">
    <td colspan="8" class="text-center bg-warning">No customer</td>
  </tr>
{% endfor %}

Reward/templates/Reward/includes/partial_customer_list4.html
{% for book in books %}
<tr style="width:1000PX"> 
    <td>{{ book.fname }}</td>
    <td>{{ book.lname }}</td>
    <td>{{ book.phone}}</td>
    <td>{{ book.score}}</td>
    <td>{{ book.date}}</td>
<td>{{ book.fscore}}</td>

 
  </tr>
{% empty %}
  <tr style="width:1000PX">
    <td colspan="8" class="text-center bg-warning">No customer</td>
  </tr>
{% endfor %}

Reward/templates/Reward/includes/partial_customer_update.html
<form method="post" action="{% url 'Reward:book_update' form.instance.pk %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Customer</h4>
  </div>
  <div class="modal-body">
    {% include 'Reward/includes/partial_customer_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update customer</button>
  </div>
</form>