Reward/urls.py
from django.conf.urls import url
from django.contrib import admin
from Reward import views
from django.urls import include, path


app_name = 'Reward'
urlpatterns = [
    path('customer_dash', views.customer_dash, name='customer_dash'),
    path('login_user', views.login_user, name='login_user'),
    path('logt', views.logout_view, name='logt'),
    path('customer_reward', views.customer_reward, name='customer_reward'),
    path('rating', views.rating, name='rating'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('customer_report', views.customer_report, name='customer_report'),
    path('customer_details/<int:id>/', views.customer_details, name='customer_details'),
    path('export_customer_csv', views.export_customer_csv, name='export_customer_csv'),
    path('export_customer_csv2', views.export_customer_csv2, name='export_customer_csv2'),
    
    path('customers_report_list', views.customers_report_list, name='customers_report_list'),
    path('<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('<int:pk>/update/', views.customer_update, name='book_update'),
    path('create', views.customer_create, name='book_create'),
    path('create', views.customer_list, name='book_list'),
    path('search', views.search, name='search'),
    
   
]

customerReward/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Reward import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name="landing"),
    path('Reward/', include('Reward.urls', namespace='Reward'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Reward/models.py
# -*- coding: utf-8 -*-


from django.db import models
from datetime import datetime
# Create your models here.




from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings

class UserDetail(models.Model):
    user = models.ForeignKey(on_delete=models.CASCADE, to=User)
    gender = models.CharField(max_length=10)



    


# How to access any field of Register model from views.py Using  built in User model  of django 
# 1.request.user.register.telno or  request.user.register.city  or request.user.register.state or  request.user.register.role2
class Register(models.Model):

    user = models.ForeignKey(User, blank=True, default=False,on_delete=models.CASCADE, related_name="register")
    fname = models.CharField(blank=True, max_length=20,  default=False)
    sname = models.CharField(blank=True, max_length=30,  default=False)
    page = models.IntegerField(blank=True,  default=False)
    gender = models.CharField(blank=True, max_length=30,  default=False)
    telno = models.CharField(blank=True, max_length=20,  default=False)
    username = models.CharField(blank=True, max_length=20,default=False)
    password= models.CharField(max_length=50,  default=False)
    email = models.CharField(blank=True,max_length=50,  default=False)
    street = models.CharField(blank=True,max_length=50,  default=False)
    city = models.CharField(blank=True,max_length=20, default=False)
    state = models.CharField(blank=True,max_length=20,  default=False)
    role2 = models.CharField(max_length=20, default=False)
    access_right= models.CharField(max_length=30,default=False)
    account_blocked = models.BooleanField(default=False)
    profphoto = models.ImageField(upload_to ='uploads/', default=False) 
    code = models.CharField(max_length=12, blank=True,default=False)
    reward_amount = models.DecimalField(max_digits=16,
        decimal_places=5, default=0.0)


    
    def get_names(self):
        '''
        Return a users phonenumber
        '''
        text = '%s %s' % (self.fname, self.lname)
        try:
            text = text.encode('utf-8')
        except UnicodeEncodeError:
            pass
        return text

    def __unicode__(self):
        return self.username




@receiver(post_save, sender=User)
def create_user_register(sender, instance, created, **kwargs):
    if created:
        Register.objects.create(user=instance)



class Customer(models.Model):
 
    '''store login data'''
    date = models.DateTimeField(auto_now_add=True)
    fname = models.CharField(blank=True,max_length=50,  default=False)
    lname= models.CharField(blank=True,max_length=50,  default=False)
    phone = models.CharField(blank=True,max_length=50,  default=False)
    avscore = models.CharField(blank=True,max_length=50,  default=0)
    num_free = models.CharField(blank=True,max_length=50,  default=0)

class Rating(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    fname = models.CharField(blank=True,max_length=50,  default=False)
    lname= models.CharField(blank=True,max_length=50,  default=False)
    fullname = models.CharField(blank=True,max_length=50,  default=False)
    phone = models.CharField(blank=True,max_length=50,  default=False)
    score = models.FloatField()
    avscore = models.CharField(blank=True,max_length=50,  default=0)
    fscore = models.CharField(blank=True,max_length=50,  default=0)

    def __str__(self):
        return str(self.pk)

    @property
    def getavstar(self):
        if self.avscore == '':
            return 'None'
        return self.avscore




    

Reward/forms.py
from django import forms
from .models import Customer

from django.db import models

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('fname','lname', 'phone', )

Reward/views.py
from django.http import HttpResponse, Http404

from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User 
import re
from django.db.models import Avg, Max, Min, Sum
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from Reward.models import Rating
from Reward.models import Register 

from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login as auth_login
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth import logout


import csv

from django.http import HttpResponse

from django.views.decorators.csrf import csrf_exempt
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.conf import settings

from django.contrib import messages
import string 

import json
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
import datetime 
from django.db.models import Q
from Reward.utils import success_message, error_message
from django.http import JsonResponse
from django.template.loader import render_to_string
import random
import string

# payment

import requests
import time
from xml.etree import ElementTree as etree
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)   
import xmltodict
import json
import datetime
from datetime import timedelta
from lxml import objectify as xml_objectify



from django.shortcuts import render,get_object_or_404
from .models import  Customer
from .forms import  CustomerForm
from django.template.loader import render_to_string
from django.http import JsonResponse





# Video chat imports
import requests
import base64
import json
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.conf import settings
import random


def search(request):
    if request.is_ajax():
        q = request.GET.get('q')
        if q is not None:            
            results = Customer.objects.filter(  
                Q( fname__contains = q ) |
                Q( lname__contains = q ) )  
            context = {'results': results}        
            return render(request, 'Reward/results.html', context) 

         




@login_required
def render_view(request, template, data):
    '''
    wrapper for rendering views , loads RequestContext
    @request  request object
    @template  string
    @data  tumple
    '''
    context = RequestContext(request)

    # store login info

    # user permissions
    if request.user.is_authenticated():
        permissions = (request.user)
        print("User permissions %s " % (permissions))
        profile = {}
        try:
            profile = Register.objects.filter(user=request.user)
        except PageNotAnInteger:
            if request.user.is_superuser:
                create_superuser(request.user)         
                
        data.update({'profile': profile, 'perms': permissions})
    # for pagnation
    #debug(permissions, 'permissions')

    return render(request, template, data) 
  
   
   







def create_superuser(user):
    '''we are not doing this'''
    profile = Register.objects.create(user=user)



def get_user_permissions(user):
    '''return user permissions as a dict'''
    permissions = {}
    for x in Permission.objects.filter(user=user):
        permissions.update({x.codename: True})
    return permissions

    




def customer_dash(request):
    """Index page, force login here"""
    latest_questions = None
    context = RequestContext(request)

    context = {
    'latest_questions': latest_questions,
}

  
    return render(request, 'Reward/index.html', context) 







def logout_view(request):
    logout(request)
    return render(request,'Reward/index.html')
 



def landing(request):
    """Index page, force login here"""
    latest_questions = None
    context = RequestContext(request) 

    context = {
    'latest_questions': latest_questions,
}

    

    if  request.user.is_authenticated:
        print("User loged in")
        return render(request, 'Reward/login_user.html', context) 

  

    return render(request, 'Reward/login_user.html', context) 




@csrf_exempt
def login_user(request):
    # Like before, obtain the context for the user's hrequest.
    context = RequestContext(request)
    msg = ''
    response = None
    log = False
    convmem = ''
    phonedoctor = ''
    data = {}
    password = None
    username = None
    pay_status = None
    staf=False
    auth_error = False
    dname = None
    check_user = None
    dp_room1 = None
    dp_room = None
    check_doct = None
    dtelno=None
    type = None
    doctor_users =None
    doctor_users = None
    doctor_sms_data = {}
    ilness= ''
    role = None
    ordered_drugs = None
    query = None
    labtests = None

  

    try:
        check_user = Register.objects.get(username=request.user.username)
        role = check_user.role2
    except Exception as e:
        pass

    print("ROLEE")
    print(role)


    
    print("USEEERRR LOGGGGGGGG")
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        password = request.POST.get('password', None)
        username = request.POST.get('username', None)
        

        print("")
        try:
            check_user = Register.objects.get(password=password, username=username)
            role = check_user.role2
           
            print("Role %s" %(role))


        except Register.DoesNotExist:
            listing = None
           
            auth_error = True
            return render(request, 'Reward/login_user.html', {'log':log, 'auth_error':auth_error}) 
            
            
                

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
               



                print("Username", username)
                print("Password", password)

                request.session['username'] = request.user.username
                request.session['role'] = role



                print("Username 1", username)
                print("Password 1", password)
               
                return render(request, 'Reward/index.html', {'role':role, 'username':username}) 
                
                 


    return render(request, "Reward/login_user.html", {
        
            })






def dashboard(request):
    
    response = False
    post_values = {}
    context = RequestContext(request)
    Check_area = None
    saved_results = ''
    dp_room = ''
    username  = ''
    context = RequestContext(request)

    staff_no = " "
    staff_name  = " "
    labtest = True
   #GETTING RECORDS OF SQLITE3 
    saved_results=Customer.objects.order_by('-id')

    print(("Length %s" % (len(saved_results))))
    a = len(saved_results)
    role="customer_care"

    paginator = Paginator(saved_results, 10) # 6 posts per page
    page = request.GET.get('page')



    try:
        saved_results = paginator.page(page)
    except PageNotAnInteger:
        saved_results = paginator.page(1)
    except EmptyPage:
        saved_results = paginator.page(paginator.num_pages)




    try:
        if a >= 1:
            return render(request, 'Reward/dashboard.html', {'role':role,'books':saved_results}) 
    except Exception as e:
        return render(request, 'Reward/dashboard.html', {'role':role,'books':saved_results,'role':role}) 

    return render(request, 'Reward/dashboard2.html', {'role':role, 'books':saved_results}) 






@csrf_exempt
def rating(request):
    context = RequestContext(request)
    post_values = {}
    push_notif = {}
    AfricasTalk = None
    AfricasTalk  = AfricasTalk
    doctor_sms_data = {}
    dp_room = None
    password = None
    dname = None
    pdiog = None
    dtelno = None
    ptelno = None
    ge_city = None
    telno = ''
    doctor_users = None
    check_phone= None

    us = None
    dtelno = ''
    gender = None
    username = None
    check_record = None
    check_score  = None
    addedscore = False
    lname = None
    cust_score=None
    doctor_none = False
    if 'username' in request.session:
        username = request.session['username']
        print("Seesssion Username of Reward %s" % (username))

    
        
    if request.POST:
       
        post_values = request.POST.copy()
        fname = request.POST.get('fname', False)
        customer_id = request.POST.get('customer_id', False)
        

        free_product = request.POST.get('free_product', 0)
        rating = request.POST.get('rating', False)
        rating=float(rating)
        print("Rating %s" % (rating))

        try:
            check_record = Customer.objects.get(id=customer_id)
        except Exception as e:
            pass

        check_phone =   check_record.phone
        lname =   check_record.lname
        fname2 =   check_record.fname  
        fullname = "%s %s" % (fname2,lname)
        if fname and fname2:

            cust_score=Rating(fname=fname,lname=lname, fullname=fullname,
             score= int(rating), fscore=free_product, phone=check_phone)
            cust_score.save()

        if cust_score:
             addedscore= True

        try:
            check_scores = Rating.objects.filter(fname=fname)
        except Exception as e:

Reward/templates/Reward/base_reward.html
{% load static %}

<!--     for  django bootstrap themes
-->

<!doctype html>
<html lang="en">

<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link href="{% static 'vendor/fonts/circular-std/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'libs/css/style.css' %}">
<link rel="stylesheet" href="{% static 'vendor/fonts/fontawesome/css/fontawesome-all.css' %}">
<link rel="stylesheet" href="{% static 'vendor/charts/chartist-bundle/chartist.css' %}">
<link rel="stylesheet" href="{% static 'vendor/charts/morris-bundle/morris.css' %}">
<link rel="stylesheet" href="{% static 'vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/charts/c3charts/c3.css' %}">
<link rel="stylesheet" href="{% static 'vendor/fonts/flag-icon-css/flag-icon.min.css' %}">

<!-- table records and pagination tab -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.pagination.css' %}">



<link rel="stylesheet" href="{% static 'css/inline-valid/style_swal_msg.css' %}" />

{% block stylesheet %}


{% endblock %}



<style type="text/css">




</style>

<title>Customer </title>
</head>

<body>
<!-- ============================================================== -->
<!-- main wrapper -->
<!-- ============================================================== -->
<div class="dashboard-main-wrapper">
<!-- ============================================================== -->
<!-- navbar -->
<!-- ============================================================== -->
<div class="dashboard-header">
<nav class="navbar navbar-expand-lg bg-white fixed-top">
<a class="navbar-brand" href="index.html"></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse " id="navbarSupportedContent">
<ul class="navbar-nav mr-auto menu">


<div class="dropdown bg-light">
<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

    
My Account
</button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

<a class="dropdown-item" href="{% url 'landing'  %}">Logout</a>
</div>
</div>





</ul>
</div>
</nav>
</div>
<!-- ============================================================== -->
<!-- end navbar -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- left sidebar -->
<!-- ============================================================== -->
<div class="nav-left-sidebar sidebar-dark">
<div class="menu-list">
<nav class="navbar navbar-expand-lg navbar-light">
<a class="d-xl-none d-lg-none" href="#">Dashboard</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
<ul class="navbar-nav flex-column">
<li class="nav-divider">
Menu
</li>
<li class="nav-item ">
<a class="nav-link active" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1" aria-controls="submenu-1"><i class="fa fa-fw fa-user-circle"></i>Dashboard <span class="badge badge-success">6</span></a>

<div id="submenu-1" class=" submenu" style="">
<ul class="nav flex-column">
<li class="nav-item">
<a class="nav-link" href="#" data-toggle="collap" aria-expanded="false" data-target="#submenu-1-2" aria-controls="submenu-1-2" style="width:700px;">Welcome {{ user.username }}</a>
</li>
<div id="submenu-1-2" class="submenu" style="">
<ul class="nav flex-column">

<li class="nav-item">
<a class="nav-link" href="{% url 'Reward:customer_dash' %}">Dashboard</a>
</li>


<li class="nav-item">
<a class="nav-link"  href="{% url 'Reward:dashboard' %}">Customer Master</a>
</li>

<li class="nav-item">
<a class="nav-link"  href="{% url 'Reward:customer_reward' %}">Customer Rewards</a>
</li>



<li class="nav-item">
<a class="nav-link" href="{% url 'Reward:customer_report' %}">Rewards Report</a>
</li>

<li class="nav-item">
<a class="nav-link" href="{% url 'landing'  %}">Logout</a>
</li>


<li class="nav-item">
<!--   <a class="nav-link" href="ecommerce-product-checkout.html">Product Checkout</a> -->
</li>
</ul>
</div>



</li>


</ul>
</div>
</li>

</ul>
</div>
</nav>
</div>
</div>
<!-- ============================================================== -->
<!-- end left sidebar -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- wrapper  -->
<!-- ============================================================== -->
<div class="dashboard-wrapper">

<div class="container">




{% block content %}                                                
{% endblock %}  






<!-- ============================================================== -->
<!-- footer -->
<!-- ============================================================== -->
<!-- Start:- Footer  -->
<footer class="footer-content p-2 " id="aBCFooter" style="margin-left:680; background: #ffab62;margin-top: 700px;
width: 100%;
height: 100%;
/* position: absolute; - remove this*/
/* bottom: 0; - remove this*/
/* left: 0; - remove this*/">
<span>
&copy; <span >2021</span> <a href="http://instorerewards.co/" target="_blank">Instore Rewards.</a> All RightReserved. 
</span>
<a href="https://b.link/appsupport" target="_blank">
<span>Customer Support</span>
</a>
</footer>                    <!-- End:- Footer  -->

<!-- ============================================================== -->
<!-- end footer -->
<!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- end wrapper  -->
<!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- end main wrapper  -->
<!-- ============================================================== -->
<!-- Optional JavaScript -->
<!-- jquery 3.3.1 -->
<script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>



<!-- bootstap bundle js -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap-paginator.js' %}"></script>



<!-- slimscroll js -->
<script src="{% static 'vendor/slimscroll/jquery.slimscroll.js' %}"></script>
<!-- main js -->
<script src="{% static 'libs/js/main-js.js' %}"></script>
<!-- chart chartist js -->
<script src="{% static 'vendor/charts/chartist-bundle/chartist.min.js' %}"></script>
<!-- sparkline js -->
<script src="{% static 'vendor/charts/sparkline/jquery.sparkline.js' %}"></script>
<!-- morris js -->
<script src="{% static 'vendor/charts/morris-bundle/raphael.min.js' %}"></script>
<script src="{% static 'vendor/charts/morris-bundle/morris.js' %}"></script>
<!-- chart c3 js -->
<script src="{% static 'vendor/charts/c3charts/c3.min.js' %}"></script>
<script src="{% static 'vendor/charts/c3charts/d3-5.4.0.min.js' %}"></script>
<script src="{% static 'vendor/charts/c3charts/C3chartjs.js' %}"></script>
<script src="{% static 'libs/js/dashboard-ecommerce.js' %}"></script>



<script src="{% static 'js/inline-valid/main.js' %}"></script>
<script src="{% static 'js/inline-valid/jquery.min.js' %}"></script>
<!-- Foundation & FontAwesome -->
<link rel="stylesheet" type="text/css" href="{% static 'css/inline-valid/foundation.css' %}">
<script src="{% static 'js/inline-valid/d3.v3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/inline-valid/trianglify.min.js' %}"></script>


<script src="{% static 'js/inline-valid/jquery-1.12.2.min.js' %}"></script>
<script src="{% static 'js/inline-valid/sweetalert2.js' %}"></script>


<!-- Inline validation -->

<script src="{% static 'js/inline-valid/tooltipster.bundle.min.js' %}"></script>
<script src="{% static 'js/inline-valid/jquery.min.js' %}"></script>
<script src="{% static 'js/inline-valid/jquery.validate.js' %}"></script>
<script src="{% static 'js/inline-valid/additional-methods.js' %}"></script>

<script type="text/javascript">

$.validator.addMethod('h_telno', function (value, element) {
value = value.replace(/\s+/g, "");
return this.optional(element) || value.length > 9 &&
value.match(/^((\+[1-9]{1,4}[ \-]*)|(\([0-9]{2,3}\)[ \-]*)|([0-9]{2,4})[ \-]*)*?[0-9]{3,4}?[ \-]*[0-9]{3,4}?$/);
}, "Please enter a valid phone number");


$.validator.addMethod("anyDate",
function(value, element) {
return value.match(/^(0?[1-9]|[12][0-9]|3[0-1])[/., -](0?[1-9]|1[0-2])[/., -](19|20)?\d{2}$/);
},
"Valid date required!"
);

$(document).ready(function() {

$("#labtest-form2").validate({
ignore:"input[type='text']:hidden",
rules: {
city : {
required: true,
},

Area : {
required: true,
},
member2: {
required: true,
},
member : {
required: true,
},
telno : {
required: true,
h_telno: true
},

username: {
required: true,
minlength: 3
},

address : {
required: true,
minlength: 3
},
weight: {
required: {
depends: function(elem) {
return $("#age").val() > 50
}
},
number: true,
min: 0
}
},



messages : {


username: {
required:"Username is required",
minlength: "username should be at least 3 characters"
},

address: {
required:"Address is required",
minlength: "Address should be at least 3 characters"
},
telno: {
required:"phonenumber is required",
},

weight: {
required: "People with age over 50 have to enter their weight",
number: "Please enter your weight as a numerical value"
}
},

errorPlacement: function(error, element) {

if (element.attr("name") == "emp[]") {

error.appendTo( element.parent("td"));
}
else {
error.insertAfter(element);
}
}

});






// validate ambulance
//ity,Area, address, countryCode, phone, username, deliv_fee, 
$("#post-form2").validate({
ignore:"input[type='text']:hidden",
rules: {
city : {
required: true,
},

Area : {
required: true,
},
address : {
required: true,
minlength: 3
},
phone : {
required: true,
h_telno: true
},
username: {
required: true,
minlength: 3
},


weight: {
required: {
depends: function(elem) {
return $("#age").val() > 50
}
},
number: true,
min: 0
}
},



messages : {

username: {
required:"Username is required",
minlength: "username should be at least 3 characters"
},

address: {
required:"Address is required",
minlength: "Address should be at least 3 characters"
},
weight: {
required: "People with age over 50 have to enter their weight",
number: "Please enter your weight as a numerical value"
}
},

errorPlacement: function(error, element) {

if (element.attr("name") == "emp[]") {

error.appendTo( element.parent("td"));
}
else {
error.insertAfter(element);
}
}

});  //end ambulance valid


// validate Medicines
//ity,Area, address, countryCode, phone, username, deliv_fee, 
$("#med_form").validate({
ignore:"input[type='text']:hidden",
rules: {
city : {
required: true,
},

area : {
required: true,
},
address : {
required: true,
minlength: 3
},
telno : {
required: true,
h_telno: true
},
username: {
required: true,
minlength: 3
},
age:{
required: true,
integer: true
},

weight: {
required: {
depends: function(elem) {
return $("#age").val() > 50
}
},
number: true,
min: 0
}
},



messages : {

username: {
required:"Username is required",
minlength: "username should be at least 3 characters"
},

address: {
required:"Address is required",
minlength: "Address should be at least 3 characters"
},
age: {
required:"Age is required",
integer: "only integers required"
},
weight: {
required: "People with age over 50 have to enter their weight",
number: "Please enter your weight as a numerical value"
}
},

errorPlacement: function(error, element) {

if (element.attr("name") == "emp[]") {

error.appendTo( element.parent("td"));
}
else {
error.insertAfter(element);
}
}

});  //end Medicine valid

// validate Illness
//illness,telno, username,city, dname
$("#illness_form").validate({
ignore:"input[type='text']:hidden",
rules: {
illness : {
required: true,
minlength:8
},
telno : {
required: true,
h_telno: true
},
username: {
required: true,
minlength: 3
},
dname: {
required: true,
},

name: {
required: true,
},
fever: {
required: true,
},
cough: {
required: true,
},
contwith: {
required: true,
},
moved: {
required: true,
},
district: {
required: true,
},

breath: {
required: true,
},



weight: {
required: {
depends: function(elem) {
return $("#age").val() > 50
}
},
number: true,
min: 0
}
},



messages : {

username: {
required:"Username is required",
minlength: "username should be at least 3 characters"
},

weight: {
required: "People with age over 50 have to enter their weight",
number: "Please enter your weight as a numerical value"
}
},

errorPlacement: function(error, element) {

if (element.attr("name") == "emp[]") {

error.appendTo( element.parent("td"));
}
else {
error.insertAfter(element);
}
}

});  //end Illness  valid



});




$(document).ready(function () { 
$(document).ajaxStart(function () {
$('#wait').show();
});
$(document).ajaxStop(function () {
$('#wait').hide();
});
$(document).ajaxError(function () {
$('#wait').hide();
});   
});

</script>

{% block javascript %}

{% endblock %}


</body>

</html>

Reward/templates/Reward/customer_report2.html
{% extends "Reward/customer_report.html" %}

Reward/templates/Reward/customer_reward2.html
{% extends "Reward/customer_reward.html" %}

Reward/templates/Reward/customers_report_list2.html
{% extends "Reward/customers_report_list.html" %}

Reward/templates/Reward/javascript.html
{% load static %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

Reward/templates/Reward/login_user.html
{% extends 'Reward/base2.html' %}
{% load static %}


{% if auth_error %}

    <strong>
    <script>alert("Invalid Username or Password")</script>
    </strong>

{% endif %}
 


{% block content %}




 {% include "Reward/login.html" %}



    

  {% endblock %}


    

Reward/templates/Reward/results.html
{% if results|length %}
	
{% for r in results %}
<option value="{{r.id}}">{{ r.fname }} {{ r.lname}}</option>
{% endfor %}


{% else %}
	
{% endif %}